#!/usr/bin/env python2.6
# Copyright (c) 2010 Mitch Garnaat http://garnaat.org/
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
from optparse import OptionParser
import os
import pynas.uploader

Usage = "usage: %prog [options]"

if __name__ == "__main__":
    parser = OptionParser(usage=Usage)
    parser.add_option("-i", "--index", action="store", type="string",
                      dest='index_path', help="Path to index",
                      default="~/.pynas")
    parser.add_option("-b", "--bucket", action="store", type="string",
                      dest='bucket_name', help="S3 bucket name",
                      default="pynas")
    parser.add_option("-p", "--processes", action="store", type="int",
                      dest='num_processes', help="Number of upload workers",
                      default=4)
    options, args = parser.parse_args()
    if len(args) != 0:
        parser.error('unknown arguments')
    index_path = os.path.expanduser(options.index_path)
    u = pynas.uploader.Uploader(index_path, options.bucket_name,
                                options.num_processes)
    u.main()
